package ru.raralux.itunesfs.service.model

data class TrackModel(
    var wrapperType: String? = null,
    var kind: String? = null,
    var artistId: Int? = null,
    var collectionId: Long? = null,
    var trackId: Int? = null,
    var artistName: String? = null,
    var collectionName: String? = null,
    var trackName: String? = null,
    var collectionCensoredName: String? = null,
    var trackCensoredName: String? = null,
    var artistViewUrl: String? = null,
    var collectionViewUrl: String? = null,
    var trackViewUrl: String? = null,
    var previewUrl: String? = null,
    var artworkUrl30: String? = null,
    var artworkUrl60: String? = null,
    var artworkUrl100: String? = null,
    var collectionPrice: Float? = null,
    var trackPrice: Float? = null,
    var releaseDate: String? = null,
    var collectionExplicitness: String? = null,
    var trackExplicitness: String? = null,
    var discCount: Int? = null,
    var discNumber: Int? = null,
    var trackCount: Int? = null,
    var trackNumber: Int? = null,
    var trackTimeMillis: Long? = null,
    var country: String? = null,
    var currency: String? = null,
    var primaryGenreName: String? = null,
    var isStreamable: Boolean? = null
)
